# Page settings

baseurl = "https://mmejia.me/"
languageCode = "en-us"
title = "Marlon Mejia"
theme = "hugo-orbit-theme"
# googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Marlon Mejia"
    author = "Marlon Mejia"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-7.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Marlon"
        tagline = "Datacenter Engineer"
    #    avatar = "profile.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: hire@mmejia.me"
        title = "hire@mmejia.me"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+16314807675"
        title = "+1-631-480-7675"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "//mmejia.me"
        title = "mmejia.me"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
	    url = "//www.linkedin.com/in/marlon-mejia/"
        title = "linkedin.com/in/marlon-mejia"

        # [[params.contact.list]]
        # class = "github"
        # icon = "fa-github"
        # url = "//github.com/username"
        # title = "github.com/username"

        # [[params.contact.list]]
        # class = "twitter"
        # icon = "fa-twitter"
        # url = "//twitter.com/username"
        # title = "@twittername"

    # Education section
    # [params.education]
    #     enable = false
    #     title = "Education"

    #     [[params.education.list]]
    #     degree = "MSc in Computer Science"
    #     college = "University of London"
    #     dates = "2006 - 2010"

    #     [[params.education.list]]
    #     degree = "BSc in Applied Mathematics"
    #     college = "Bristol University"
    #     dates = "2007 - 2011"

    # Education section
    # [params.education]
    #     enable = true
    #     title = "Certifications"

    #     [[params.education.list]]
    #     degree = "MSc in Computer Science"
    #     college = "University of London"
    #     dates = "2006 - 2010"

    #     [[params.education.list]]
    #     degree = "BSc in Applied Mathematics"
    #     college = "Bristol University"
    #     dates = "2007 - 2011"

    # Certification section
    [params.certifications]
        enable = true
        url = "https://www.credly.com/users/marlon-mejia.d46c58af/badges"
        title = "Certifications"

        [[params.certifications.list]]
        certification = "RHCSA"

        [[params.certifications.list]]
        certification = "Comptia A+"

        [[params.certifications.list]]
        certification = "Comptia Security+"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Proficient"

        [[params.language.list]]
        language = "Spanish"
        level = "Proficient"

    # Interests section
    # [params.interests]
    #     enable = true
    #     title = "Interests"

    #     [[params.interests.list]]
    #     interest = "Basketball"

    #     [[params.interests.list]]
    #     interest = "Running"

    #     [[params.interests.list]]
    #     interest = "Hiking"

    #     [[params.interests.list]]
    #     interest = "Technology"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = """Working with **Bloomberg LP** as a frontline engineer supporting our hardware and platforms within our datacenters. 
        \n Troubleshooting a wide arange of hardware and services for our customers or within our datacenter."""

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Datacenter Hardware Engineer"
        dates = "2020 - Present"
        company = "Bloomberg LP, New Jersey"
        details = """- Troubleshooting more than 10,000 application systems for ***Windows, Linux. AIX and Solaris***.
        \n- Troubleshooting more than 10,000 network devices including ***Arista, Juniper, ArcOS, Nvidia, Cisco, Brocade***.
        \n- **Collaborated** with hardware vendors to create automation of case opening and log gathering on multiple systems and network devices using **REST APIs** and **Python**.
        \n- Contributed in updating legacy and outdated **documentation and scripts** via **Github** using **Python** and **Bash**
        \n- Front line troubleshooting any of our network disruptions, applications or cluster failures to provide a ***High Availability*** within our datacenters.
        \n- Monitor Operating System and Network Hardware for any network disruptions, resource utilization or power utilization within our data center via ***Grafana, Splunk and Humio.***"""

        [[params.jobs.list]]
        position = "Datacenter Technician"
        dates = "2020 - 2020"
        company = "New York Internet, New York"
        details = """- Provide Hands-on services to customers for any given tasks such as mounting a KVM, Cross-Connect, Rebooting of Devices, Configuration of devices, Removal or Addition of components.
        \n- Monitor in-house ticket system as well as ***LogicMonitor, ConnectWise*** and ***Meraki*** for outages, circuit issues, ***Switches or Routers*** interfaces as well as networking issues such as ***DDoS, Abuse Reports and DNS Records***.
        \n- ***Mount and Rack*** servers, switches and routers to cabinets for clients in a methodical way while keeping in mind cable management and power management.
        \n- Automation of Google Drive copy, editing and uploading with ***Python*** for spreadsheets, docs and files."""

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        # intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

        [[params.projects.list]]
        title = "My Resume"
        url = "https://mmejia.me/"
        tagline = """- Used **S3 Buckets** to store files for a static website, that is now Proxied with **CloudDistribution** for faster delivery.
        \n- Used **Route 53** to correctly route my domains and mail servers. 
        \n- **Cert Manager** to create a certificate for security.
        \n- Used **CodePipeline** to automate the deployment of my website with [**HUGO**](https://hugothemesfree.com/my-cv-resume-using-a-free-hugo-theme/) to test and deploy my website via a pipeline."""

        [[params.projects.list]]
        title = "Python REST API"
        url = ""
        tagline = """Collaborated with hardware vendors to create workflows, modules and scripts to create, gather and upload logs for our network devices with [**Juniper API**](https://eng.juniper.net/site/global/build/support_automation/service_api/case_api/index.gsp") and [**Cisco ServiceGrid API**](https://www.cisco.com/c/dam/en_us/partners/downloads/partner/WWChannels/download/atp/cisco-servicegrid-customer-ebc.pdf)"""

        [[params.projects.list]]
        title = "Terraform & Ansible Automation"
        url = ""
        tagline = "Used **Terraform** to deploy a VM Instance in Oracle Cloud to be made into my VPN. **Ansible** was used to configure the server to install and run a docker container with Wireguard."

        [[params.projects.list]]
        title = "Docker"
        url = ""
        tagline = """Deployed with **Ansible** for containers such as ***OpenVPN, Wireguard, DokuWiki, Adguard, ZNC, LetsEncrypt, MySQL, Wordpress, AdGuardHome*** within my homelab."""

        [[params.projects.list]]
        title = "Site-2-Site VPN"
        url = ""
        tagline = "AWS and PfSense Site 2 Site IPsec Tunnel to connect my cloud network to a segmented network of my homelab."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Python, Bash & Powershell"
        level = "95%"

        [[params.skills.list]]
        skill = "CI/CD & Git"
        level = "90%" 

	[[params.skills.list]]
        skill = "Ansible, Terraform & SaltStack"
        level = "70%"

        [[params.skills.list]]
        skill = "HTML5 & CSS"
        level = "95%"

        [[params.skills.list]]
        skill = "AWS"
        level = "75%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = ""
