name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: ["Build resume"]
    types:
      - completed

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  deploy:
    permissions:
      contents: write
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v1