name: Build resume

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y pandoc texlive texlive-xetex

    - name: Convert Markdown to PDF
      run: pandoc resume.md -o resume.pdf --pdf-engine=xelatex

    - name: Convert Markdown to DOCX
      run: pandoc resume.md -o resume.docx

    - name: Convert Markdown to HTML
      run: pandoc resume.md -o index.html

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: |
          resume.pdf
          resume.docx
          index.html
