name: Convert resume

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y pandoc texlive texlive-xetex

    - name: Convert Markdown to PDF
      run: pandoc resume.md -o resume.pdf --pdf-engine=xelatex

    - name: Convert Markdown to DOCX
      run: pandoc resume.md -o resume.docx

    - name: Convert Markdown to HTML
      run: pandoc resume.md -o index.html

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: resume-files
        path: |
          resume.pdf
          resume.docx
          index.html
          
  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action