name: Build resume

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y pandoc texlive texlive-xetex

    - name: Convert Markdown to PDF
      run: pandoc resume.md --standalone --css=styling.css -o resume.pdf

    - name: Convert Markdown to DOCX
      run: pandoc resume.md --standalone --css=styling.css -o resume.docx

    - name: Convert Markdown to HTML
      run: pandoc resume.md --standalone --css=styling.css -o index.html

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: '.'

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: github-pages
        path: .

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
